# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  environment.impermanence = {
    enable = true;
    device = "/dev/disk/by-uuid/dcb5b5bc-a1b7-4488-ae65-5cf70195357d";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F113-143A";
    fsType = "vfat";
  };

  fileSystems."/.btr_pool" = {
    device = "/dev/disk/by-uuid/dcb5b5bc-a1b7-4488-ae65-5cf70195357d";
    fsType = "btrfs";
    options = [
      "subvolid=5"
      "compress-force=zstd"
      "noatime"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/dcb5b5bc-a1b7-4488-ae65-5cf70195357d";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "compress-force=zstd"
      "noatime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/dcb5b5bc-a1b7-4488-ae65-5cf70195357d";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress-force=zstd"
    ];
  };

  fileSystems."/.swap" = {
    device = "/dev/disk/by-uuid/dcb5b5bc-a1b7-4488-ae65-5cf70195357d";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
      "nodatacow"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
